"""empty message

Revision ID: baf810b68a4f
Revises: 973048c3547a
Create Date: 2023-12-08 12:24:49.733028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baf810b68a4f'
down_revision = '973048c3547a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=128),
               type_=sa.String(length=162),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=162),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
